// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbxKUCSIX5Ihw7PXTDg4ibVN56tSneCEo',
    appId: '1:167819210428:web:aa52360d1ba928a9282ab9',
    messagingSenderId: '167819210428',
    projectId: 'chat-app-tharwat',
    authDomain: 'chat-app-tharwat.firebaseapp.com',
    storageBucket: 'chat-app-tharwat.appspot.com',
    measurementId: 'G-N72C71Z6GL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU1ButgY6Wgsc7TsaayamDHn4gatNs7bA',
    appId: '1:167819210428:android:4768b6712ee98df4282ab9',
    messagingSenderId: '167819210428',
    projectId: 'chat-app-tharwat',
    storageBucket: 'chat-app-tharwat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDrgBoX3T_4Cm-wSyxHhJHo6hRdr1lZtE',
    appId: '1:167819210428:ios:d211c23ecba27368282ab9',
    messagingSenderId: '167819210428',
    projectId: 'chat-app-tharwat',
    storageBucket: 'chat-app-tharwat.appspot.com',
    iosClientId: '167819210428-s9lulqpva3lf51roeqlhdoqld8tthi2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
